version: 2

before:
  hooks:
    - go mod tidy

builds:
  - binary: uniforge
    env:
      - CGO_ENABLED=0
    goos:
      - linux
      - windows
      - darwin
    goarch:
      - amd64
      - arm64
    ignore:
      - goos: windows
        goarch: arm64
    ldflags:
      - -s -w -X main.version={{.Version}}

archives:
  - name_template: "uniforge_{{ .Os }}_{{ .Arch }}"
    files:
      - LICENSE*
      - README*

checksum:
  name_template: 'checksums.txt'

snapshot:
  version_template: "{{ incpatch .Version }}-next"

changelog:
  sort: asc
  filters:
    exclude:
      - '^docs:'
      - '^test:'
      - '^chore:'
      - '^ci:'
      - '^build:'
      - '^refactor:'
      - '^style:'
      - '^perf:'
    include:
      - '^feat:'
      - '^fix:'
      - '^BREAKING CHANGE:'

brews:
  - repository:
      owner: neptaco
      name: homebrew-tap
      token: "{{ .Env.HOMEBREW_TAP_GITHUB_TOKEN }}"
    directory: Formula
    homepage: https://github.com/neptaco/uniforge
    description: CLI tool for Unity development
    license: MIT
    install: |
      bin.install "uniforge"
    test: |
      system "#{bin}/uniforge", "--version"

scoops:
  - repository:
      owner: neptaco
      name: scoop-bucket
      token: "{{ .Env.SCOOP_TAP_GITHUB_TOKEN }}"
    homepage: https://github.com/neptaco/uniforge
    description: CLI tool for Unity development
    license: MIT