version: 2

project_name: uniforge

before:
  hooks:
    - go mod tidy

builds:
  - binary: uniforge
    env:
      - CGO_ENABLED=0
    goos:
      - linux
      - windows
      - darwin
    goarch:
      - amd64
      - arm64
    ignore:
      - goos: windows
        goarch: arm64
    ldflags:
      - -s -w -X main.version={{.Version}}

archives:
  - name_template: "uniforge_{{ .Os }}_{{ .Arch }}"
    files:
      - LICENSE*
      - README*

checksum:
  name_template: 'checksums.txt'

snapshot:
  version_template: "{{ incpatch .Version }}-next"

changelog:
  sort: asc
  filters:
    exclude:
      - '^docs:'
      - '^test:'
      - '^chore:'
      - '^ci:'
      - '^build:'
      - '^refactor:'
      - '^style:'
      - '^perf:'
    include:
      - '^feat(\(.*\))?!?:'
      - '^fix(\(.*\))?!?:'
      - '^BREAKING CHANGE:'
